spring.application.name=backend
## spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

## Oauth2
spring.security.oauth2.client.registration.google.client-id=1023403202873-4m8hcvrlgr54mjoj3b81q1ts530gfki7.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

## baza
##spring.datasource.url=jdbc:postgresql://localhost:5432/juliusmeinl
## ========== DATABASE CONFIGURATION ==========
spring.datasource.url=jdbc:postgresql://dpg-d4s5uqh5pdvs73c0bsr0-a.frankfurt-postgres.render.com:5432/hotel_postgres
spring.datasource.username=hotel_postgres_user
spring.datasource.password=5lMLs148pq5tozn90Ez7Bk2bIcjl5L7D

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

frontend.url=https://lukaomr.vercel.app

##error ispis
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
